---

- hosts: web 
  tasks:
  - name: Install Tree Package
    apt: name=tree state=present

 
  - name: Install Apache Package
    apt: name=apache2 state=present


  - name: Start Apache Service 
    service: name=apache2 state=started



- hosts: all 
  tasks:
  - name: Disable Firewall Service 
    service: name=ufw state=started

