---

- hosts: 172.31.0.101
  name: "WebServer Deployment - PLAY" 
  become: true 
  tasks:
  - name: Install Apache Package
    apt: name=apache2 state=present
    when: ansible_os_family == "Debian"

  - name: Install HTTPD Package
    yum: name=apache2 state=present
    when: ansible_os_family == "RedHat"

  - name: Start Apache Service 
    service: name=apache2 state=started
    when: ansible_os_family == "Debian"

 
  - name: Start HTTPD Service 
    service: name=httpd state=started
    when: ansible_os_family == "Redhat"

  - name: Deploy Custom Index Web Page
    copy: src=files/index.html dest=/var/www/html/index.html
