---

- hosts: 172.31.0.101
  name: "WebServer Deployment - PLAY" 
  become: true 
  tasks:
  - name: Install Apache Package
    apt: name=apache2 state=present
    when: ansible_os_family == "Debian"

  - name: Install HTTPD Package
    yum: name=httpd state=present
    when: ansible_os_family == "RedHat"

  - name: Start Apache Service 
    service: name=apache2 state=started
    when: ansible_os_family == "Debian"

 
  - name: Start HTTPD Service 
    service: name=httpd state=started
    when: ansible_os_family == "RedHat"

  - name: Deploy Custom Index Web Page
    copy: src=files/index.html dest=/var/www/html/index.html


  - name: Check the web info file exits or not ? 
    command: ls /var/www/html/info-1.html
    register: inforesult
    ignore_errors: yes



  - debug: msg="Unable to Locate the info-1.html file"
    when: inforesult is failed   

  - debug: msg="Able to Locate the info-1.html file"
    when: inforesult is succeeded 

  - name: Deploy Custom Info Web Page
    copy: src=files/info.html dest=/var/www/html/info-1.html
    when: inforesult is failed   
