---
# handlers file for webserver

- name: Restart Apache
  service: name=apache2 state=restarted
  when: ansible_os_family == "Debian"
- name: amit
  shell: 'echo "Welcome to Handlers Demo - {{ansible_hostname}}, Now Apache Port No. is -> {{http_port}}" >> /tmp/handlers.txt'
